/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class FileDialog {
  constructor()
  addFilter(name: string, ext: Array<string>): this
  setDirectory(dir: string): this
  setFileName(name: string): this
  setTitle(title: string): this
  pickFile(): string | null
  pickFiles(): Array<string> | null
  pickFolder(): string | null
  pickFolders(): Array<string> | null
  saveFile(): string | null
}
