/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum MessageLevel {
  Info = 0,
  Warning = 1,
  Error = 2
}
export const enum MessageButtons {
  Ok = 0,
  OkCancel = 1,
  YesNo = 2
}
export class FileDialog {
  constructor()
  addFilter(name: string, ext: Array<string>): this
  setDirectory(dir: string): this
  setFileName(name: string): this
  setTitle(title: string): this
  pickFile(): string | null
  pickFiles(): Array<string> | null
  pickFolder(): string | null
  pickFolders(): Array<string> | null
  saveFile(): string | null
}
export class AsyncFileDialog {
  constructor()
  addFilter(name: string, ext: Array<string>): this
  setDirectory(dir: string): this
  setFileName(name: string): this
  setTitle(title: string): this
  pickFile(): Promise<FileHandle | null>
  pickFiles(): Promise<Array<FileHandle> | null>
  pickFolder(): Promise<FileHandle | null>
  pickFolders(): Promise<Array<FileHandle> | null>
  saveFile(): Promise<FileHandle | null>
}
export class FileHandle {
  static wrap(pathBuf: string): FileHandle
  fileName(): string
  path(): string | null
  read(): Promise<Array<number>>
  toString(): string
}
export class MessageDialog {
  constructor()
  setLevel(level: MessageLevel): this
  setTitle(title: string): this
  setDescription(description: string): this
  setButtons(buttons: MessageButtons): this
  show(): boolean
}
